app:
  port: "8322"
  upload_file_path: "D:\\GoLang\\gin\\tmp_images\\"
  cookie_key: "4238uihfieh49r3453kjdfg"
  serve_type: "GoServe"
  debug_mode: "true"

mysql:
  dsn: "root:root@tcp(127.0.0.1:3306)/gin?charset=utf8mb4&parseTime=True&loc=Local"
